---
name: idr0042-nirschl-wsideeplearning/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ;
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:

  - name: Channels
    clientname: Channels
    include: yes
  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes
  - name: Characteristics [Diagnosis]
    clientname: Diagnosis
    include: yes
  - name: Characteristics [Disease subtype]
    clientname: Disease subtype
    include: yes
  - name: Characteristics [Sex]
    clientname: Sex
    include: yes
  - name: Characteristics [Ethnic or Racial group]
    clientname: Ethnic or Racial group
    include: yes
  - name: Characteristics [Age in years]
    clientname: Age in years
    include: yes

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes
